### ISSUE TITLE
"Abstract" types

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#10]
From the fantasy-land [Monad](https://github.com/fantasyland/fantasy-land#monad) specification.

 > A value which satisfies the specification of a Monad does not need to implement:

>  * Apply's ap; derivable as function(m) { return this.chain(function(f) { return m.map(f); }); }
 * Functor's map; derivable as function(f) { var m = this; return m.chain(function(a) { return m.of(f(a)); })}

This could mean that we could create this type:
 ```
function Monad() {}
Monad.prototype.ap = function(m) { return this.chain(function(f) { return m.map(f); }); }
Monad.prototype.map = function(f) { var m = this; return m.chain(function(a) { return m.of(f(a)); })}
```

.. and then implement stuff like
```
function Maybe() {};
inherits(Maybe, Monad);

function Just() {};
inherits(Just, Maybe);

Just.prototype.of = ...
Just.prototype.chain = ...
```

This also removes the need to test if the type has all the monadic functions. All that is required is to assert it is an instance of ```Monad```.

There are also other examples of functions that can be derived from other types.
Good/bad idea?

**Comment by CrossEye** [comment]
While such is possible, we might want custom versions of such key features as `map` and `ap` and not depend on the inheritance mechanism.  Ofttimes, thinking of `Maybe` as a Functor is all we need, which means that we care only about the `map` implementation.

**Comment by TheLudd** [comment]
Then just don't extend ```Monad``` for ```Maybe```. And you can still overwrite specific implementations if that is wanted. 

I just thought it would be a cool thing if it is the purpose of this project to be fantasy land compatible.

**Comment by CrossEye** [comment]
Absolutely the goal is to be FantasyLand compatible.  The FantasyLand spec is odd.  It lets you know some of the laws you need to fulfill, but offers little help in determining how to fulfill them.  One bit of help it does offer, though, is this style of, "Hey, if you're doing X, you could choose to skip Y, since the laws imply that Y can be derived from X like this..."  While this is nice to know, and perhaps make for an implementation more likely to follow the laws, it doesn't necessarily lead to either intuitive code or code that is as performant as it might be.

The point in caring about `Maybe` as a Functor is that we might often want to call `map` over a `Maybe` and we would like a clean `map` function to do that.  The fact that `Maybe` is also an Applicative and therefore the laws imply that `map` can be derived from `ap` and `of` is less relevant.

**Comment by TheLudd** [comment]
Closing this for now since the recent future change (#26) would not have fitted in with this. Similar problems may occur for other types.
