### ISSUE TITLE
Maybe as a Semigroup?

### ISSUE THREAD

**Issue by i-am-tom** [ramda/ramda-fantasy#122]
Hello!

Firstly, this project is great, and I've been playing with it for a few weeks. I have to ask, though: is there a reason why Maybe doesn't have a `concat` method defined? As I see it, the concatenation would work like this:

```haskell
Nothing `concat` Nothing = Nothing
Nothing `concat` x = x
x `concat` Nothing = x
(Just x) `concat` (Just y) = Just (x `concat` y)
```

I'm more than happy to submit the PR if this sounds reasonable - just thought I'd double check in case I'd missed something obvious :)

**Comment by davidchambers** [comment]
That's the way [`S.Maybe#concat`][1] is defined.

There's significant overlap between ramda-fantasy and Sanctuary. There's been talk of merging the two projects, in #105 and perhaps in other threads, to avoid further duplication of effort.

I imagine a pull request to define `Maybe#concat` would be accepted, particularly since what you're proposing is compatible with Sanctuary and would thus not be a source of conflict if and when we merge the projects. :)


[1]: https://sanctuary.js.org/#Maybe.prototype.concat

**Comment by buzzdecafe** [comment]
what @davidchambers said. i'd be happy to see a pr on this.

**Comment by TheLudd** [comment]
Are the middle cases valid?
```
Nothing `concat` x = x
x `concat` Nothing = x
```

Should it not be like this?
```
Nothing `concat` (Just x) = (Just x)
(Just x) `concat` Nothing = (Just x)
```

**Comment by i-am-tom** [comment]
Would they not both achieve the same results? Either way, it was just a brief explanation :)

I should have a PR ready by the end of the day!

**Comment by TheLudd** [comment]
I am saying that `Nothing `concat` x = x` violates the contract unless `x` is an instance of `Maybe`.

> `concat` must return a value of the same Semigroup.

https://github.com/fantasyland/fantasy-land#semigroup

**Comment by i-am-tom** [comment]
Ah, beg your pardon. What I was writing was meant to look more like the `instance` implementation for a Maybe type in Haskell. Still, as long as the idea is otherwise sound, I'll press on :)

**Comment by i-am-tom** [comment]
Closing - PR's at #123 !
