### ISSUE TITLE
Get this party started?

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#5]
Hello @CrossEye @buzzdecafe @davidchambers! 
I don't know what the plan for ```ramda-fantasy``` is but recently I have begun using monads in my programming and since I love ```ramda``` I would also love for the ramda community to maintain its own type library unless the maintainers of ramda think that there are better alternatives out there in the wild.

Looking at this repo, what I initially see is missing is:
 * Tests
 * Build system
 * Code cleanup
 * Code documentation
 * Website

I am of course willing to help our here, to contribute and learn more about how to do functional programming right. I am curious what the rest of the people invested in ramda thinks.

**Comment by buzzdecafe** [comment]
Hello @TheLudd! 

The plan is no plan -- I haven't had time to dedicate to this project. I agree that the types have turned into neglected step-children. 

Ramda should be compatible with any library that satisfies the https://github.com/fantasyland/fantasy-land spec although I am sure there are gaps in that coverage (e.g. `Monoid.concat`). So that should feed back into Ramda. fantasy-land has a list of conformant implementations here: https://github.com/fantasyland/fantasy-land/blob/master/implementations.md

I also recommend you take a look at https://github.com/plaid/sanctuary by @davidchambers which is coming along nicely, and is getting battle-tested in the wild (unless I am mistaken). It is not fantasy-land compatible, and I don't know if that is a goal of @davidchambers for the project.

> I am of course willing to help our here, to contribute and learn more about how to do functional programming right.

That sounds 100% in accord with my goals -- any help you want to offer would be gratefully accepted!

> I am curious what the rest of the people invested in ramda thinks.

:+1:  Let's do it

**Comment by TheLudd** [comment]
Alright, sounds like fun :)

What are you opinions on the existing code base and which would be the first steps to go from where we are today?

**Comment by CrossEye** [comment]
Like all of Ramda, this was as much a learning exercise as a serious attempt at building out something useful to others.  Nonetheless, there was a reasonable amount of thought put into them, mostly by @buzzdecafe (with some input from me), and I think they work pretty well.  The test suite is fairly minimal, but it is there.

At one point my hope had been for these extensions to be things that could be easily built into custom versions of Ramda proper, possibly even offering overrides for various basic functions.  I think that's probably gone now.  But these could still easily be packaged individually as `ramda.monad.js`, `ramda.either.js`, etc., or as a combined, `ramda.types.js` that might or might not have any dependencies on Ramda, but with which Ramda could easily interoperate.

**Comment by buzzdecafe** [comment]
> What are you opinions on the existing code base and which would be the first steps to go from where we are today?

* `Maybe` should be pretty solid; 
* `Either` is good, if idiosyncratic; I don't think anyone else is currying the `Either` constructor -- that was my idea, and maybe it isn't right.
* `Future` is mostly cribbed from folktale, my understanding of it is not deep.
* `IO` I'm not fully comfortable with either. Probably cribbed a lot from folktale and dr. boolean. 
* `Reader` is by @donnut I believe, and I think that is pretty solid too.

Actually, we should get @donnut involved if we can, because I believe he has been using these types.

On the to-do list are all the things you mentioned, plus:

* I'd love a `Promise` monad, 
* while i'm dreaming, it would be great to have a way of wrapping existing promise libs for monadic behavior. that would be kick ass.
* gotta add "methods" for the `Monoid` functions
* gotta bring these implementations up to spec w/r/t `Extend` and `Comonad`
* I'd like to see "tests that prove that these implementations satisfy the algebraic *laws*. I'm not sure how to go about doing that though; unit tests seem inadequate to the task.

**Comment by donnut** [comment]
I'm using `IO` extensively (to handle DOM) and that works fine. Used Maybe and Either at a certain stages in our project, but removed them because using them during prototyping was to much hassle. 
On my list (for a long time) is the state and state transformer monad. I would love to improve on handling state in one class, but postponed it to the refactoring stage. 
If time permites I'm more than willing to participate, I'm a big fan om Ramda.

**Comment by TheLudd** [comment]
I have noticed that you use commonjs for ramda but not really in this project. Could a first step be to commonjsify the existing modules? After that they can perhaps be published to npm with an alpha label or something like that.

**Comment by buzzdecafe** [comment]
sounds good

**Comment by TheLudd** [comment]
As a warm up I thought I'd start with making the tests pass in #6

**Comment by buzzdecafe** [comment]
i think this party is now officially started
