### ISSUE TITLE
Tuple Applicative Behaviour

### ISSUE THREAD

**Issue by scott-christopher** [ramda/ramda-fantasy#51]
As briefly discussed on Gitter, the current Applicative implementation for `Tuple` doesn't behave.

```js
Tuple.of(R.identity).ap(Tuple.of({}));
//=> [TypeError: function f1(a) { ... } be a semigroup to perform this operation]
```

I currently see three options here:
- (1) Downgrade Tuple to `Apply` by dropping `of`.

- (2) Change the current `ap` implementation to:
```js
_Tuple.prototype.ap = function(m) {
  return Tuple(this[0](m[0]), this[1](m[1]));
};
```

- (3) Change the current `of` implementation to something like:
```js
Tuple.of = function(x) {
  return Tuple({ concat: R.identity }, x);
};
```

I think I'd like to see `Tuple` take on option 2 and if desirable, introducing a `Writer` type that can implement option 3, but I'm keen to hear the thoughts of others.

**Comment by joneshf** [comment]
Option 1 is the only sensible one.

Option 2 will break the `Apply` law unless `map` is changed as well, then the type becomes specifically a tuple for two of the same type, ala haskell `data Tuple a = Tuple a a`. While this is probably a fine implementation for certain things, it's probably not what many people think of when they want a `Tuple`.

Option 3 still breaks the `Applicative` laws (and maybe others). In particular it'll break the interchange law, since `concat` isn't commutative.

As far as `Writer`, well it already is:

```javascript
RF.Tuple("", R.add).ap(RF.Tuple("wat ", 3)).ap(RF.Tuple("yup", 4))
{ '0': 'wat yup', '1': 7, length: 2 }
```

If the `Chain` implementation is added, it can make it easier to use though. We could add things like `tell` and friends:

```javascript
function tell(x) { return RF.Tuple(x, null); }
RF.Tuple('', 3).chain(function(x) { 
  return tell(x.toString())
    .chain(R.always(tell(' ')))
    .chain(R.always(tell('is')))
    .chain(R.always(tell(' ')))
    .chain(R.always(tell('the')))
    .chain(R.always(tell(' ')))
    .chain(R.always(tell('value')))
    .chain(R.always(RF.Tuple('', x)))
    .map(R.multiply(10)); 
});
//=> { '0': '3 is the value', '1': 30, length: 2 }
```

**Comment by buzzdecafe** [comment]
simplest is probably to drop `of` from `Tuple` because of the difficulties of working around it.

Aside: It seems to me we need a `Chain` column in the table, since should we add `chain` to `Tuple` it'll be a `chain` but not a `Monad`.
