### ISSUE TITLE
IO tests fail with ramda 0.17

### ISSUE THREAD

**Issue by TheLudd** [ramda/ramda-fantasy#63]
I was trying to upgrade to ramda `0.17.x` but the tests for `IO` fail. I can't really see why. Does anyone else have an idea?

**Comment by davidchambers** [comment]
What is the error?

**Comment by TheLudd** [comment]
The standard `applicative.id` test. The difference is that with ramda `0.15` one execution of `runIO` returns `'undefined2'` but with ramda `0.17` it returns a function.

**Comment by joneshf** [comment]
A while back I was finding all sorts of bugs in the tests: #20, #22 are two issues about that. Could be related. I've wanted to help change the tests, but sadly no time.

**Comment by scott-christopher** [comment]
I believe it's because `R.compose` in `IO.map` now returns a curried function, so calling `IO.runIO` with no arguments as it does in `IO.equals` will return the same curried function rather calling it with no args. For example, changing `IO.equals` to the following allows the tests to pass:
```js
R.equals(IO.runIO(this, 'x'), IO.runIO(that, 'x'));
```

I personally think we need to get rid of both `IO.equals` and `Reader.equals`, as they're both unreliable for testing equality.

The `Reader` tests has tripped me up in the past too. I started refactoring the tests to allow an equality function to be passed in instead, rather than relying on `.equals`, but got distracted somewhere along the way and don't know where I left it.

**Comment by scott-christopher** [comment]
Sorry, it looks like `IO.chain` also needs to be modified to pass on the `arguments` in order for the tests to all pass.
```patch
IO.prototype.chain = function(f) {
  var io = this;
  return new IO(function() {
-    return f(io.fn()).fn();
+    var next = f(io.fn.apply(io, arguments));
+    return next.fn.apply(next, arguments);
  });
};
```
I'm not entirely sure that arguments should be passed via `runIO`, but if we want to support it then this will should be fixed.

**Comment by joneshf** [comment]
> The Reader tests have tripped me up in the past too. I started refactoring the tests to allow an equality function to be passed in instead, rather than relying on .equals, but got distracted somewhere along the way and don't know where I left it

Hah! Same thing here :)

**Comment by TheLudd** [comment]
@scott-christopher 

> I personally think we need to get rid of both IO.equals and Reader.equals, as they're both unreliable for testing equality.

Perhaps do as with `Future`. Add an equals method in the tests that is suitable for a controlled test environment but not available in the wild?
